### ISSUE TITLE
exceptions when installing eggs should print their stdout

### ISSUE THREAD

**Issue by toumorokoshi** [toumorokoshi/uranium#5]
This exception was hidden by uranium:

    You are using pip version 7.1.0, however version 7.1.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    Collecting py.test
    Downloading py.test-0.0.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
        File "<string>", line 20, in <module>
        File "/private/var/folders/cl/94kcfkt53p5805wlmbm7kcmw0000gp/T/pip-build-S0Z8Ri/py.test/setup.py", line 6, in <module>
            raise ValueError("please use 'pytest' pypi package instead of 'py.test'")
        ValueError: please use 'pytest' pypi package instead of 'py.test'

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/cl/94kcfkt53p5805wlmbm7kcmw0000gp/T/pip-build-S0Z8Ri/py.test

We should expose that, somehow.

**Comment by toumorokoshi** [comment]
this is done, by adding pip's logging to the list of accepted log output.
